M48
; DRILL file {KiCad 9.0.1} date 2025-08-22T17:09:04+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-22T17:09:04+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
%
G90
G05
T1
X142.256Y-97.556
T2
X144.944Y-100.244
M30
